flock: our second project!
gofrs/website pull request #3
Opened 2018-09-30 03:59 UTC by adamdecaf

I noticed it wasn't listed today, so I threw something together. Figure it's good press for the projects too!

2018-10-05 05:12 UTC, theckman requested changes
This looks good, with one piece of feedback about the second section. How do you feel about it?

2018-10-05 05:12 UTC, theckman commented on content/projects/flock/_index.md
> +Overall, the project seems stable and complete. There aren't a tons and tons of users, but some important projects. ([Import list](https://godoc.org/github.com/theckman/go-flock?importers))
I would combine these two sentences:
>Based on its issue and PR history the project seems stable and complete, with some impactful projects making use of it.

2018-10-07 16:16 UTC, adamdecaf commented on content/projects/flock/_index.md
> +Overall, the project seems stable and complete. There aren't a tons and tons of users, but some important projects. ([Import list](https://godoc.org/github.com/theckman/go-flock?importers))
Yea, that reads much better.

2019-01-10 02:28 UTC, niaow approved these changes
LGTM

2019-01-10 17:53 UTC, adamdecaf commented
cc @theckman

2024-06-29 01:31 UTC, ldez commented
I will merge this PR even if the website is dead.

I think I will work on a new website.

2024-06-29 01:31 UTC, merged